name: 30-Day Tweet Scheduler

# This action will run on a schedule.
on:
  schedule:
    - cron: '50 6 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest # Use a standard Linux environment

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # Action to get your code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the tweet posting script
      env:
        # These secrets are injected as environment variables
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: python post_tweet.py

    - name: Commit and push if CSV changed
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add tweets.csv
        # Commit only if there are changes
        git diff --staged --quiet || git commit -m "Update tweet status via GitHub Actions"
        git push